#!/bin/bash


if [ "$#" -lt 1 ]
then
    src="."
else
    src=$1
fi

git init $src
cd $src
echo '*~' > .gitignore
echo 'build' >> .gitignore
echo '__py*' >> .gitignore
touch READEME.md
git add .
git commit -m "initial"
