#! /bin/bash
#
#

echo "Entering Library repo:"
cd ~/Library
git add .
git commit -m "udpate"
git pull
git push
echo -e "\n\n"

echo "Enterring fealpy: "
cd ~/work/fealpy/
git add .
git commit -m "update"
git pull
git push
echo -e "\n\n"

echo "Entering fealpy-example:"
cd ~/work/fealpy-example/
git add .
git commit -m "udpate"
git pull
git push
echo -e "\n\n"

echo "Entering tool:"
cd ~/work/tool/
git add .
git commit -m "update"
git pull
git push
echo -e "\n\n"

echo "Entering whyvim:"
cd ~/work/whyvim/
git add .
git commit -m "update"
git pull
git push
echo -e "\n\n"

echo "Entering iwrite:"
cd ~/work/iwrite
git add .
git commit -m "udpate"
git pull
git push
echo -e "\n\n"

echo "Entering whysite:"
cd ~/work/whysite/
./gitbook.sh
echo "\n\n"

echo "Entering numopde:"
cd ~/work/numopde/
./gitbook.sh
echo -e "\n\n"

echo "Entering numal:"
cd ~/work/numal/
./gitbook.sh
echo -e "\n\n"
