#! /bin/bash
#
#

git_workflow () {
    git add .
    git commit -m "udpate"
    git pull
    git push
    echo -e "\n\n"
}

echo "Entering Library repo:"
cd ~/Library
CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ];then
    git_workflow
else
    git pull
fi

echo "Enterring fealpy: "
cd ~/work/fealpy/
CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ];then
    git_workflow
else
    git pull
fi

echo "Entering fealpy-example:"
cd ~/work/fealpy-example/
CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ];then
    git_workflow
else
    git pull
fi

echo "Entering tool:"
cd ~/work/tool/
CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ];then
    git_workflow
else
    git pull
fi

echo "Entering whyvim:"
cd ~/work/whyvim/
CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ];then
    git_workflow
else
    git pull
fi

echo "Entering iwrite:"
cd ~/work/iwrite
CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ];then
    git_workflow
else
    git pull
fi
echo -e "\n\n"

echo "Entering whysite:"
cd ~/work/whysite/
./gitbook.sh
echo -e "\n\n"

echo "Entering numopde:"
cd ~/work/numopde/
./gitbook.sh
echo -e "\n\n"

echo "Entering numal:"
cd ~/work/numal/
./gitbook.sh
echo -e "\n\n"
