#!/bin/bash
#
# 每次更新系统都需要做很多手工的配置，为了提高效率，特编写下面的脚本，
# 记录下配置的过程，方便以后使用。
#

GITHUB = https://github.com/weihuayi
git clone ${GITHUB}/tool.git

## Clone 常用的工作目录

hg clone https://whymath@bitbucket.org/ifem/ifem

git config --global user.email "weihuayi@xtu.edu.cn"
git config --global user.name "Huayi Wei"

git clone ${GITHUB}/vim.git
git clone ${GITHUB}/fealpy.git 

##　clone 私有仓库
git clone https://whymath@bitbucket.org/whymath/gearfem.git
git clone https://whymath@bitbucket.org/whymath/gearopt.git

## clone 课件仓库
git clone https://github.com/weihuayi/ODE.git

## clone 学生仓库
